language: python
python:
  - 3.6
before_install:
  - python3 -m pip install -r ./requirements/requirements.txt
script:
  - make html
deploy:
  provider: pages
  local-dir: ./build/html
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master